name: CI Pipeline

on:
  push:
    branches:
      - main
      - release/**
      - feature/**
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            **/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Permission go Gradlew
        run: chmod +x ./gradlew

      - name: Set YML
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml
          find src

      - name: Build with Gradle
        run: ./gradlew build

      - name: Login Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image and Push
        env:
          NAME: ${{ secrets.DOCKER_NAME }}
          REPO: ${{ secrets.DOCKER_REPO_NAME }}
        run: |
          export SHORT_SHA=$(echo ${{ github.sha }} | cut -c 1-8)
          docker build -t $NAME/$REPO:$SHORT_SHA -t $NAME/$REPO:latest -f Dockerfile .
          docker push $NAME/$REPO:$SHORT_SHA
          
