# 1 워크플로의 이름 지정
name: dev CI Pipeline

# 2 워크플로가 시작될 조건 지정
on:
  push:
    branches:
      - ci/cd-workflow

jobs:
  build:
    runs-on: ubuntu-latest # 3 실행 환경 지정
    #4 실행스텝지정
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            **/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Permission go Gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        env:
          ENV: ${{ secrets.APPLICATION_YML_DEV }}
        run: |
          mkdir src/main/resources
          echo "$ENV" > src/main/resources/application.yml
          ./gradlew build

      - name: Test
        env:
          ENV: ${{ secrets.APPLICATION_YML_DEV }}
        run: |
          mkdir src/main/resources
          echo "$ENV" > src/main/resources/application.yml
          ./gradlew test
