name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            **/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Permission go Gradlew
        run: chmod +x ./gradlew

      - name: Set YML
        run: |
          mkdir -p src/main/resources
          if [[ $GITHUB_REF_NAME == 'main' ]]; then
            echo "${{ secrets.ENV_PROD }}" | base64 --decode > src/main/resources/application.yml
          else
            echo "${{ secrets.ENV_DEV }}" | base64 --decode > src/main/resources/application.yml
          fi
          find src

      - name: Build Docker image
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c 1-8)
          docker build . -t reservation:$SHORT_SHA -f Dockerfile


